# Generated by Django 2.0.7 on 2018-07-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180724_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodCategory',
            new_name='GoodsCategory',
        ),
        migrations.AddField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='goods.GoodsCategory', verbose_name='商品类目'),
            preserve_default=False,
        ),
    ]
